version: "3.8"
services:
  db:
    image: postgres:12.14
    container_name: postgresql-db-data
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bdpep1
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
  app:
    container_name: pep1tingeso
    image: holyadio/pep1tingeso
    ports:
      - "8090:8090"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bdpep1
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
